# Declare the quantity of dockers we will deploy
services:
  # Microservice dockerization
  lalu_events_ms:
    # Define a new name to the container on Docker
    container_name: lalu_events_ms
    # Take the dockerfile in the same directory and creates an image
    build: .
    # Declare ports
    ports:
      - 8080:8080
    # Define the enviroments variables that are being used on the Dockerfile
    environment:
      DEPLOY_PROFILE: prod

      # Database dockerization
  # lalu_events_db:
    # Take the dockerfile in the same directory and creates an image
    # build: ./database
    # Define a new name to the container on Docker
    # container_name: lalu_events_db
    # For persistence, create a volume that contains the DB data
    # volumes:
      # - lalu-events-db:/var/lib/mysql
    # Declare ports
    # ports:
      # - 3306:3306
    # Define the user that have privilegies on DB and the root pw
    # environment:
      # LANG: C.UTF-8
      # MYSQL_ROOT_PASSWORD: Forever21ROOT*
      # This command was put on the Dockerfile of the database
      # MYSQL_DATABASE: lalu_events_db
      # MYSQL_USER: laluevents
      # MYSQL_PASSWORD: Lalu*eventsPW

# volumes:
  # lalu-events-db: