# Image from the Docker repo of MYSQL (Expose ports include)
# FROM mysql:latest
# Define the database that will create and where the script will be executed
# ENV MYSQL_DATABASE lalu_events_db
# Move the script to the directory on the docker where it will be initialized
# COPY ./script.sql /docker-entrypoint-initdb.d/